env:
  browser: true
  es2021: true
  'jest/globals': true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "unused-imports"
  - "import"
  - "jest"
rules:
  "@typescript-eslint/no-unused-vars": off
  "unused-imports/no-unused-imports": error
  "unused-imports/no-unused-vars": warn
  "import/order": error
  "array-bracket-spacing": 
    - error
    - always
  "comma-spacing":
    - error
    - after: true
  "object-curly-spacing":
    - error
    - always
  "max-len":
    - error
    - code: 80
  "quotes": 
    - error
    - "double"
  "indent":
    - error
    - 2
